version: '3.8'

services:
  pterodactyl:
    image: pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_URL=https://your-domain.com
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pterodactyl
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=your_password
    volumes:
      - ./pterodactyl:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: pterodactyl_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=pterodactyl
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./db:/var/lib/mysql
